### PR TITLE
Add PHP support

### PR DESCRIPTION
**Pull request by jbrooksuk**
I feel like I've done something wrong here as this doesn't seem to work in my test repository, https://github.com/jbrooksuk/ActionServerlessPHP

But it's a start!

### CODE REVIEW

**Comment by gingerhot** [comment]
@jbrooksuk Thank you for contribution! I can see there're some problems:
1. I updated workflow config, you need rebase the code
2. Here also need update when you add a new language: https://github.com/JamesForks/ActionServerless/blob/php-support/parse_funcs.py#L8
3. all the result here is generated by the action workflow, it is not the ground truth for the test. That means you need not to create such a file. If the action works for the new language, there will be such a generated file
4. I advise that you don't support dependency installation at present to realize a minimal support for PHP at first step:https://github.com/JamesForks/ActionServerless/blob/php-support/run_funcs.py#L44

Thanks again for your contribution!

**Comment by jbrooksuk** [comment]
Thanks @gingerhot! I have made the changes now.

**Comment by jbrooksuk** [comment]
It works! https://github.com/jbrooksuk/ActionServerlessPHP/blob/master/test_hello_world_php

**Comment by gingerhot** [comment]
Great! Would you please squash the commits as single commit?  Then I will merge this pr.  Thank you again.

**Pull request merged**
